version: '3.4'

services:
  bookservice:
    image: ${DOCKER_REGISTRY-}bookservice
    build:
      context: .
      dockerfile: BookService/Dockerfile

  authorservice:
    image: ${DOCKER_REGISTRY-}authorservice
    build:
      context: .
      dockerfile: AuthorService/Dockerfile


  loanservice:
    image: ${DOCKER_REGISTRY-}loanservice
    build:
      context: .
      dockerfile: LoanService/Dockerfile

